# Generated by Django 3.2.7 on 2021-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_entry_subtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
    ]
