# Generated by Django 3.2.7 on 2021-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210921_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
